name: Update Version
on:
  push:
    tags:
      - 'v*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Git tag
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update version.go
        run: |
          echo "package main" > version.go
          echo "" >> version.go
          echo "const version = \"$TAG\"" >> version.go

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git checkout -b temp-action-branch
          git add version.go
          git commit -m "chore: update version to $TAG [skip ci]"
          
          git push origin temp-action-branch:main
